<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.reactome.maven</groupId>
    <artifactId>reactome-pwp-parent</artifactId>
    <version>1.0.4</version>
    <packaging>pom</packaging>

    <name>Reactome PWP Parent</name>
    <description>
        Reactome Parent aims to centralise dependencies management
    </description>
    <url>https://github.com/reactome/reactome-parent</url>
    <organization>
        <name>The European Bioinformatics Institute</name>
        <url>https://www.ebi.ac.uk/</url>
    </organization>
    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>eragueneau</id>
            <name>Eliot Ragueneau</name>
            <email>eragueneau@ebi.ac.uk</email>
            <organization>The European Bioinformatics Institute</organization>
            <organizationUrl>https://www.ebi.ac.uk/</organizationUrl>
        </developer>
        <developer>
            <id>cqgong</id>
            <name>Chuqiao Gong</name>
            <email>cgong@ebi.ac.uk</email>
            <organization>The European Bioinformatics Institute</organization>
            <organizationUrl>https://www.ebi.ac.uk/</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:git://github.com/reactome/reactome-parent.git</connection>
        <developerConnection>scm:git:ssh://github.com:reactome/reactome-parent.git</developerConnection>
        <url>https://github.com/reactome/reactome-parent/tree/main/parents/reactome-pwp-parent</url>
    </scm>
    <distributionManagement>
        <!-- EBI repo -->
        <repository>
            <id>pst-release</id>
            <name>EBI Nexus Repository</name>
            <url>https://www.ebi.ac.uk/Tools/maven/repos/content/repositories/pst-release</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <!-- EBI SNAPSHOT repo -->
        <snapshotRepository>
            <uniqueVersion>false</uniqueVersion>
            <id>pst-snapshots</id>
            <name>EBI Nexus Snapshots Repository</name>
            <url>https://www.ebi.ac.uk/Tools/maven/repos/content/repositories/pst-snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </snapshotRepository>
    </distributionManagement>

    <properties>
        <java.version>11</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <reactome.reactome-bom.version>1.0.6</reactome.reactome-bom.version>
        <reactome.reactome-pwp-bom.version>1.0.4</reactome.reactome-pwp-bom.version>

        <!--scroller-->
        <gwtVersion>2.9.0</gwtVersion>
        <jetty.runner.version>9.4.41.v20210516</jetty.runner.version>
        <elemental2.version>1.1.0</elemental2.version>
        <junit.jupiter.version>5.8.0-M1</junit.jupiter.version>
        <slf4j.version>1.7.22</slf4j.version>

        <!--carrousel-->
        <!--shared dependencies-->

        <!--model-->
        <junit.version>4.13.2</junit.version>  <!-- gwt user uses Junit 4 -->

        <!--analysis-client-->
        <!--shared dependencies-->

        <!--diagram-->
        <lib.gwt.svg.version>0.5.11</lib.gwt.svg.version>

        <!--diagram-JS-->
        <!--fireworks-JS-->
        <gwt.exporter.version>2.4.0</gwt.exporter.version>

        <!--quadtree-->
        <!--fireworks-->
        <!--chebi-->
        <!--gxa-->
        <!--analytics-->
        <!--pdb-->
        <!--rhea-->
        <!--shared dependencies-->

        <!--maven build and plugins-->
        <maven.jar.version>3.2.0</maven.jar.version>
        <gwt.maven.version>1.0-rc-6</gwt.maven.version>
        <maven.war.version>3.3.1</maven.war.version>
        <maven.source.version>3.3.1</maven.source.version>
        <maven.deploy.version>3.0.0-M1</maven.deploy.version>
        <wagon.ssh.version>3.5.3</wagon.ssh.version>
        <maven.compiler.version>3.8.1</maven.compiler.version>
        <maven.release.version>3.3.1</maven.release.version>
        <maven.gpg.version>3.2.8</maven.gpg.version>
        <maven.javadoc.version>3.11.2</maven.javadoc.version>
        <maven.tidy.version>1.4.0</maven.tidy.version>
        <maven.sonatype.central.version>0.8.0</maven.sonatype.central.version>
    </properties>

    <dependencyManagement>
        <dependencies>

            <!--        DEFINING REACTOME PACKAGES       -->
            <dependency>
                <groupId>org.reactome.maven</groupId>
                <artifactId>reactome-bom</artifactId>
                <version>${reactome.reactome-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.reactome.maven</groupId>
                <artifactId>reactome-pwp-bom</artifactId>
                <version>${reactome.reactome-pwp-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.google.gwt</groupId>
                <artifactId>gwt</artifactId>
                <version>${gwtVersion}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!--        REACTOME PWP DEPENDENCIES       -->
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-runner</artifactId>
                <version>${jetty.runner.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>com.google.elemental2</groupId>
                <artifactId>elemental2-core</artifactId>
                <version>${elemental2.version}</version>
            </dependency>

            <dependency>
                <groupId>com.google.elemental2</groupId>
                <artifactId>elemental2-dom</artifactId>
                <version>${elemental2.version}</version>
            </dependency>

            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-api</artifactId>
                <version>${junit.jupiter.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version>
            </dependency>

            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-nop</artifactId>
                <version>${slf4j.version}</version>
            </dependency>

            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.vectomatic</groupId>
                <artifactId>lib-gwt-svg</artifactId>
                <version>${lib.gwt.svg.version}</version>
            </dependency>

            <dependency>
                <groupId>org.timepedia.exporter</groupId>
                <artifactId>gwtexporter</artifactId>
                <version>${gwt.exporter.version}</version>
                <scope>provided</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <repositories>
        <!-- EBI repo -->
        <repository>
            <id>nexus-ebi-repo</id>
            <name>The EBI internal repository</name>
            <url>https://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <!-- EBI SNAPSHOT repo -->
        <repository>
            <id>nexus-ebi-snapshot-repo</id>
            <name>The EBI internal snapshot repository</name>
            <url>https://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <build>
        <plugins>
            <!-- Creates jar file containing source (*.java) files for the project-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>${maven.source.version}</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <extensions>true</extensions>
                <version>${maven.deploy.version}</version>
            </plugin>

            <!-- Generate JavaDoc jar file -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>${maven.javadoc.version}</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Signs deployed jar, source jar, and JavaDoc jar with GPG -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>${maven.gpg.version}</version>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Allows "release" mvn goal to deploy a SNAPSHOT or version release to Sonatype -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>${maven.release.version}</version>
                <configuration>
                    <autoVersionSubmodules>true</autoVersionSubmodules>
                    <useReleaseProfile>false</useReleaseProfile>
                    <releaseProfiles>release</releaseProfiles>
                    <goals>deploy</goals>
                </configuration>
            </plugin>

            <!-- Standardizes layout of pom.xml file -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>tidy-maven-plugin</artifactId>
                <version>${maven.tidy.version}</version>
                <executions>
                    <execution>
                        <id>validate</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Allows publishing of SNAPSHOTs and releases to Sonatype staging server for Maven Central -->
            <plugin>
                <groupId>org.sonatype.central</groupId>
                <artifactId>central-publishing-maven-plugin</artifactId>
                <version>${maven.sonatype.central.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <publishingServerId>central</publishingServerId>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
